- hosts: docker
  tasks:
  - name: docker repo
    yum_repository:
      name: docker
      description: setting repo for docker-ce
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no

  - command: "yum install docker-ce --nobest -y"

  - service:
      name: docker
      state: started

  - package:
      name: python3

  - pip:
      name: docker-py

  - docker_image:
      name: httpd
      state: present

  - docker_container:
      detach: yes
      name: os_httpd
      ports: "8080:80"
      volumes: /var/www/html/:/usr/local/apache2/htdocs/:ro
      image: httpd
